name: Kotlin CI with Maven

on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - name: Run tests
        run: mvn -B clean test --file pom.xml
